print('hello world!')
print('hello python!')
print('hello pytorch!')
print('hello deeplearning!')
print('master test!')
print('hot-fix test!')
print('push test!')
print('pull test!')
print('gitee test!')
print('hello vscode')

